Repository simplepie/simplepie, pull requests merged in 2022-07, with the labels that each got.

#735 Do not use magic values for state machine state
  src/HTTP/Parser.php
  src/XML/Declaration/Parser.php
Labels: size/L

#736 Use PSR-4 classes in Registry
  src/Author.php
  src/Registry.php
Labels: size/M

#739 GH Actions: run tests against PHP 8.2
  .github/workflows/ci.yml
Labels: size/S
