Repository simplepie/simplepie, pull requests merged in 2022-10, with the labels that each got.

#751 Clarify branching strategy
  README.markdown
Labels: size/S

#753 Item::get_date: fix return type on unparsable date
  src/Item.php
Labels: size/XS

#748 Remove ROADMAP.md
  ROADMAP.md
Labels: size/S

#747 Fix error handling
  src/Misc.php
Labels: size/XS

#742 Allow usage of PSR-16 cache implementation
  CHANGELOG.md
  composer.json
  src/Cache.php
  src/Cache/Base.php
  src/Cache/File.php
  src/Cache/Memcache.php
  src/Cache/Memcached.php
  src/Cache/MySQL.php
  src/Cache/Psr16.php
  src/Cache/Redis.php
  src/Sanitize.php
  src/SimplePie.php
  tests/Fixtures/Exception/Psr16CacheException.php
  tests/Fixtures/FileMock.php
  tests/Unit/Cache/Psr16Test.php
  tests/Unit/SimplePieTest.php
Labels: size/XL

#749 Use native array_replace_recursive
  src/Cache/Memcache.php
  src/Cache/Memcached.php
  src/Cache/MySQL.php
  src/Misc.php
Labels: size/XS

#750 remove check for E_USER_DEPRECATED definition
  src/Cache.php
  src/SimplePie.php
Labels: size/S

#743 Require PHP 7.2 or newer
  .github/workflows/ci.yml
  .php-cs-fixer.dist.php
  README.markdown
  build/bootstrap.php
  build/compile.php
  compatibility_test/sp_compatibility_test.php
  composer.json
  src/Cache/Base.php
  src/HTTP/Parser.php
  src/IRI.php
  src/Misc.php
  src/Net/IPv6.php
  src/Parser.php
  src/SimplePie.php
  src/XML/Declaration/Parser.php
  tests/AllTests.php
  tests/CacheTest.php
  tests/EncodingTest.php
  tests/Fixtures/Exception/Psr16CacheException.php
  tests/LocatorTest.php
  tests/Mocks.php
  tests/SubscribeUrlTest.php
  tests/Unit/Cache/Psr16Test.php
  tests/Unit/SimplePieTest.php
  tests/bootstrap.php
Labels: size/XL
