Repository simplepie/simplepie, pull requests merged in 2022-12, with the labels that each got.

#759 Type declarations in cache
  src/Cache/BaseDataCache.php
  src/Cache/DataCache.php
  src/Cache/Psr16.php
  src/SimplePie.php
  tests/Integration/CachingTest.php
Labels: size/S

#764 Remove broken BC code in Registry
  src/Registry.php
Labels: size/S

#765 Parse\Date: Clean up regex structure
  src/Parse/Date.php
  tests/Unit/Parse/DateTest.php
Labels: size/L

#760 Create interface RegistryAware
  CHANGELOG.md
  src/Item.php
  src/Locator.php
  src/Parser.php
  src/Registry.php
  src/RegistryAware.php
  src/Sanitize.php
  src/Source.php
Labels: size/M

#767 GH Actions: update PHP versions in workflows
  .github/workflows/ci.yml
Labels: size/S
