Repository simplepie/simplepie, pull requests merged in 2023-01, with the labels that each got.

#768 No URL Decode for enclosure links
  src/Enclosure.php
  tests/Unit/EnclosureTest.php
Labels: size/M

#769 Fix case of multiple RSS2.0 enclosures
  src/Item.php
  tests/Unit/EnclosureTest.php
Labels: size/M

#771 Fix broken phpdoc references
  src/Cache/Base.php
  src/Cache/DB.php
  src/Cache/File.php
  src/Cache/Memcache.php
  src/Cache/Memcached.php
  src/Cache/MySQL.php
  src/Cache/Redis.php
  src/Parse/Date.php
Labels: size/S

#766 Registry: Allow using class-strings instead of magic strings
  src/Cache.php
  src/Item.php
  src/Locator.php
  src/Misc.php
  src/Parser.php
  src/Registry.php
  src/Sanitize.php
  src/SimplePie.php
  src/Source.php
  tests/CacheTest.php
  tests/Integration/CachingTest.php
  tests/LocatorTest.php
  tests/Unit/LocatorTest.php
  tests/Unit/RegistryTest.php
  tests/Unit/SanitizeTest.php
  tests/Unit/SimplePieTest.php
Labels: size/XL

#761 Release 1.8.0
  CHANGELOG.md
  library/SimplePie.php
  library/SimplePie/Author.php
  library/SimplePie/Cache.php
  library/SimplePie/Cache/Base.php
  library/SimplePie/Cache/DB.php
  library/SimplePie/Cache/File.php
  library/SimplePie/Cache/Memcache.php
  library/SimplePie/Cache/Memcached.php
  library/SimplePie/Cache/MySQL.php
  library/SimplePie/Cache/Redis.php
  library/SimplePie/Caption.php
  library/SimplePie/Category.php
  library/SimplePie/Content/Type/Sniffer.php
  library/SimplePie/Copyright.php
  library/SimplePie/Credit.php
  library/SimplePie/Enclosure.php
  library/SimplePie/Exception.php
  library/SimplePie/File.php
  library/SimplePie/HTTP/Parser.php
  library/SimplePie/IRI.php
  library/SimplePie/Item.php
  library/SimplePie/Locator.php
  library/SimplePie/Misc.php
  library/SimplePie/Net/IPv6.php
  library/SimplePie/Parse/Date.php
  library/SimplePie/Parser.php
  library/SimplePie/Rating.php
  library/SimplePie/Registry.php
  library/SimplePie/Restriction.php
  library/SimplePie/Sanitize.php
  library/SimplePie/Source.php
  library/SimplePie/XML/Declaration/Parser.php
  library/SimplePie/gzdecode.php
  src/Cache.php
  src/Cache/Base.php
  src/Cache/BaseDataCache.php
  src/Cache/DB.php
  src/Cache/DataCache.php
  src/Cache/File.php
  src/Cache/Memcache.php
  src/Cache/Memcached.php
  src/Cache/MySQL.php
  src/Cache/Redis.php
  src/Misc.php
  src/Registry.php
  src/SimplePie.php
Labels: size/L

#772 Constructor improvement
  src/Restriction.php
Labels: size/XS

#775 Add type hints in all classes
  .php-cs-fixer.dist.php
  library/SimplePie/Decode/HTML/Entities.php
  phpunit.xml.dist
  src/Author.php
  src/Cache.php
  src/Cache/Base.php
  src/Cache/CallableNameFilter.php
  src/Cache/DB.php
  src/Cache/File.php
  src/Cache/Memcache.php
  src/Cache/Memcached.php
  src/Cache/MySQL.php
  src/Cache/NameFilter.php
  src/Cache/Redis.php
  src/Category.php
  src/Content/Type/Sniffer.php
  src/Enclosure.php
  src/Gzdecode.php
  src/HTTP/Parser.php
  src/IRI.php
  src/Item.php
  src/Misc.php
  src/Net/IPv6.php
  src/Parse/Date.php
  src/Parser.php
  src/Registry.php
  src/Sanitize.php
  src/SimplePie.php
  src/XML/Declaration/Parser.php
  tests/CacheTest.php
  tests/Fixtures/Cache/BaseCacheWithCallbacksMock.php
  tests/ItemTest.php
  tests/Unit/SimplePieTest.php
Labels: size/L
