Repository simplepie/simplepie, pull requests merged in 2023-05, with the labels that each got.

#774 Split SimplePie\File class into HTTP client and response
  CHANGELOG.md
  src/Content/Type/Sniffer.php
  src/Exception/HttpException.php
  src/File.php
  src/HTTP/Client.php
  src/HTTP/FileClient.php
  src/HTTP/Response.php
  src/Locator.php
  src/Sanitize.php
  src/SimplePie.php
  tests/Integration/SimplePieTest.php
  tests/Unit/FileTest.php
  tests/Unit/HTTP/FileClientTest.php
  tests/Unit/LocatorTest.php
  tests/data/feed_rss-2.0_for_file_mock.xml
Labels: size/XXL

#811 ci: Add PHPStan
  .github/workflows/ci.yml
  composer.json
  phpstan.neon
Labels: size/S

#832 Fix TypeError in Sanitize::replace_urls due to a link without host
  src/Sanitize.php
Labels: size/S

#815 Split SimplePie\File class into HTTP client and response
  LICENSES/MIT.txt
  src/Content/Type/Sniffer.php
  src/File.php
  src/HTTP/Client.php
  src/HTTP/FileClient.php
  src/HTTP/Parser.php
  src/HTTP/Response.php
  src/Locator.php
  src/Misc.php
  src/Sanitize.php
  src/SimplePie.php
  tests/Integration/SimplePieTest.php
  tests/Unit/FileTest.php
  tests/Unit/HTTP/FileClientTest.php
  tests/Unit/HTTP/ParserTest.php
Labels: size/XL

#835 Move code style check into own Github Actions job
  .github/workflows/ci.yml
Labels: size/M
