Repository simplepie/simplepie, pull requests merged in 2024-07, with the labels that each got.

#865 Fix typos
  CHANGELOG.md
  phpstan.neon
  src/Cache/CallableNameFilter.php
  src/Cache/NameFilter.php
  src/HTTP/Parser.php
  src/Misc.php
  src/SimplePie.php
  tests/EncodingTest.php
  tests/IRITest.php
  tests/Integration/CachingTest.php
  tests/Unit/CategoryTest.php
  tests/Unit/IRITest.php
  tests/Unit/MiscTest.php
Labels: size/M

#862 ci: Fix php-cs-fixer
  .php-cs-fixer.dist.php
  src/SimplePie.php
Labels: size/XS

#869 Fix PHPStan for PHP 7.3
  composer.json
  src/Parser.php
Labels: size/XS

#868 PHPDoc avoid aliases for scalar types
  src/HTTP/Parser.php
  src/Item.php
  src/Misc.php
Labels: size/S

#871 Extract long repeating sanitization bases into variable
  src/Item.php
  src/SimplePie.php
  src/Source.php
Labels: size/M
