Repository simplepie/simplepie, pull requests merged in 2025-09, with the labels that each got.

#936 Normalize encoding uppercase
  src/XML/Declaration/Parser.php
Labels: size/XS

#940 PHPUnit assert functions are static
  tests/BCTest.php
  tests/CacheTest.php
  tests/EncodingTest.php
  tests/HTTPParserTest.php
  tests/IRITest.php
  tests/Integration/CachingTest.php
  tests/Integration/HTTP/ClientsTest.php
  tests/Integration/SimplePieTest.php
  tests/ItemTest.php
  tests/LocatorTest.php
  tests/SanitizeTest.php
  tests/SubscribeUrlTest.php
  tests/Unit/AuthorTest.php
  tests/Unit/Cache/BaseDataCacheTest.php
  tests/Unit/Cache/BaseTest.php
  tests/Unit/Cache/DBTest.php
  tests/Unit/Cache/FileTest.php
  tests/Unit/Cache/MemcacheTest.php
  tests/Unit/Cache/MemcachedTest.php
  tests/Unit/Cache/MySQLTest.php
  tests/Unit/Cache/Psr16Test.php
  tests/Unit/Cache/RedisTest.php
  tests/Unit/CacheTest.php
  tests/Unit/CaptionTest.php
  tests/Unit/CategoryTest.php
  tests/Unit/Content/Type/SnifferTest.php
  tests/Unit/CopyrightTest.php
  tests/Unit/CreditTest.php
  tests/Unit/EnclosureTest.php
  tests/Unit/ExceptionTest.php
  tests/Unit/FileTest.php
  tests/Unit/GzdecodeTest.php
  tests/Unit/HTTP/ParserTest.php
  tests/Unit/HTTP/Psr18ClientTest.php
  tests/Unit/HTTP/Psr7ResponseTest.php
  tests/Unit/IRITest.php
  tests/Unit/ItemTest.php
  tests/Unit/LocatorTest.php
  tests/Unit/MiscTest.php
  tests/Unit/Net/IPv6Test.php
  tests/Unit/Parse/DateTest.php
  tests/Unit/ParserTest.php
  tests/Unit/RatingTest.php
  tests/Unit/RegistryTest.php
  tests/Unit/RestrictionTest.php
  tests/Unit/SanitizeTest.php
  tests/Unit/SimplePieTest.php
  tests/Unit/SourceTest.php
  tests/Unit/XML/Declaration/ParserTest.php
Labels: size/XL

#945 File: Various clean-ups
  src/File.php
Labels: size/S
