Repository simplepie/simplepie, pull requests merged in 2025-06, with the labels that each got.

#916 Fix feeds encoded in UTF-16LE
  src/File.php
Labels: size/XS

#917 Trim body for all paths
  src/File.php
Labels: size/S

#899 Misc: Deprecate unused functions
  CHANGELOG.md
  src/Misc.php
Labels: size/S

#918 tests/Integration: Add regression tests
  tests/Integration/HTTP/ClientsTest.php
Labels: size/M

#922 tests: Improve ClientsTest::testRedirectsChain
  tests/Integration/HTTP/ClientsTest.php
Labels: size/XS

#861 Fix absolutize URL for several cases
  src/Item.php
  src/SimplePie.php
  tests/Unit/EnclosureTest.php
  tests/Unit/ItemTest.php
Labels: size/L
