Repository simplepie/simplepie, pull requests merged in 2025-08, with the labels that each got.

#933 Use correct language as identifier in Heredoc strings
  build/charset.php
  compatibility_test/sp_compatibility_test.php
  src/Misc.php
  tests/SanitizeTest.php
  tests/Unit/AuthorTest.php
  tests/Unit/CategoryTest.php
  tests/Unit/ItemTest.php
  tests/Unit/RestrictionTest.php
  tests/Unit/SanitizeTest.php
  tests/Unit/SimplePieTest.php
Labels: size/XXL

#932 Bump GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: size/S

#934 phpstan: Rename `phpstan.neon.dist` to `phpstan.dist.neon`
  phpstan.dist.neon
Labels: size/XS
